#!/bin/sh

echo "Cleaning up clients"
export NODECT=$SLURM_JOB_NUM_NODES

MPI=$(ps aux|grep srun|grep -v grep |grep $USER|awk '{print $2}')
echo "Killing launch $MPI"
kill $MPI

#sleep 5

echo "Running cleanup job"
#aprun -n $NODECT -N 1 rm -rf /tmp > /dev/null 2>&1
