#!/bin/sh

export THREADS=16
export NTHREADS=32
export HNAME=$(hostname)
export SNAME=$(grep " $HNAME " /etc/hosts|sed s'/[ \t]*#.*//'|sed 's/.* //')
export INT=ipogif0
export NODECT=$SLURM_JOB_NUM_NODES
let NODECT=$NODECT

export GET_ID="srun -Q -N $NODECT --ntasks=$NODECT cat /proc/cray_xt/nid"
export GET_IPS="srun -N $NODECT --ntasks=$NODECT /sbin/ifconfig $INT"

export RUN_DEEP="srun -N $NODECT --ntasks=$NODECT --cpus-per-task=$THREADS"
NNODECT=$(($NODECT * 2))
export NGET_ID="srun -Q -N $NNODECT --ntasks=$NNODECT --ntasks-per-socket=1  cat /proc/cray_xt/nid"

export NRUN_DEEP="srun -N $NNODECT --ntasks=$NNODECT --ntasks-per-socket=1 --cpus-per-task=$NTHREADS"

export IDCOMMAND='ID="$(cat /proc/cray_xt/nid)"'

export CRAY_ROOTFS=DSL

export HADOOP_LINK=$SCRATCH/hadoop/
export HADOOP_OPTS="-Djava.security.egd=file:/dev/urandom"
#export HADOOP_IDENT_STRING=$USER

#cp $TMPL/hadoop-env.sh $CONFIG/hadoop-env.sh

# We need to move this eventually
export HADOOP_PRELOAD=$HADOOP_YARN_LIB/libget.so

function create_env {
  printenv|grep -v '}'|grep -v '{'| sed 's/^/export /' |sed "s/=/='/" |sed "s/\$/'/" > $CONFIG/env
}
