#!/bin/sh


#export CONFIG="$HOME/.hadoop-$PBS_JOBID"

#[ -z $DEBUG_HADOOP ] || echo "runworker config_dir $CONFIG"
#[ -z $DEBUG_HADOOP ] || echo "runworker home_dir $HADOOP_HOME"
export YARN_CONF_DIR=$CONFIG
export YARN_LOG_DIR=$LOGS

[ ! -z $HADOOP_PRELOAD ] && export LD_PRELOAD=$HADOOP_PRELOAD
#[ -z $DEBUG_HADOOP ] || echo "runworker preload  $HADOOP_PRELOAD"

if [ -e "$CONFIG/env" ] ; then
  . $CONFIG/env
fi

eval "$IDCOMMAND"
[ -e $LDIR ] && rm -rf /tmp/hdfs-$USER
if [ -e $HADOOP_LINK ] ; then
  mkdir $HADOOP_LINK/$ID
  ln -s $HADOOP_LINK/$ID $LDIR
else
  mkdir $LDIR
fi
mkdir $LDIR/local


function cleanup {
  killall java > /dev/null 2>&1
  cd /tmp
  [ -e $LDIR ] && rm -rf $LDIR
  exit
}
trap cleanup 2 15

export HADOOP_IDENT_STRING=$USER
export YARN_IDENT_STRING=$USER

. $CONFIG/yarn-env.sh

if [ $(grep -c $ID $NODELIST) -gt 0 ] ;then
  export HID=$(grep ":$ID:" $NODELIST|awk -F: '{print $1}')
  if [ $HID -le $DATANODES ] ;then
  [ -z $DEBUG_HADOOP ] ||  echo "Start datanodes!"
    mkdir $LDIR/data
    bash --norc $HADOOP_HOME/sbin/hadoop-daemon.sh --config $CONFIG --script start datanode  > $LOGS/datanode.$HID 2>&1 &
#    sleep 5
  fi

  [ -z $DEBUG_HADOOP ] || echo "Starting Yarn NodeManager on $ID"
  if [ ! -z $HADOOP_PRELOAD ] ; then
    export LD_PRELOAD=$HADOOP_PRELOAD
  fi
  # Note this should NOT be the daemon
  # Daemon will return and leave a job that could be killed by aprun. nohup will not work.
  bash --norc $HADOOP_HOME/bin/yarn --config $CONFIG  start nodemanager > $LOGS/yarn.nodemanager.$ID 2>&1
  echo "Node Manager exits on $ID"
  cleanup
fi
