#!/bin/sh

#export CONFIG="$HOME/.hadoop-$SLURM_JOB_ID"

[ -z $DEBUG_HADOOP ] || echo "runworker config_dir $CONFIG"
[ -z $DEBUG_HADOOP ] || echo "runworker home_dir $HADOOP_HOME"


[ ! -z $HADOOP_PRELOAD ] && export LD_PRELOAD=$HADOOP_PRELOAD
#[ -z $DEBUG_HADOOP ] || echo "runworker preload  $HADOOP_PRELOAD"

if [ -e "$CONFIG/env" ] ; then
  . $CONFIG/env
fi

eval "$IDCOMMAND"
#echo " local dir $LDIR"
[ -e $LDIR ] && rm -rf /tmp/$BASE-$USER
if [ -e $HADOOP_LINK ] ; then
  mkdir $HADOOP_LINK/$ID
  ln -s $HADOOP_LINK/$ID $LDIR
else
  mkdir $LDIR
fi
#mkdir $LDIR/local
mkdir $LDIR/nm_local

function cleanup {
  killall java > /dev/null 2>&1
  cd /tmp
  [ -e $LDIR ] && rm -rf $LDIR
  exit
}
trap cleanup 2 15

#. $CONFIG/yarn-env.sh

if [ $(grep -c $ID $NODELIST) -gt 0 ] ;then
  export HID=$(grep ":$ID:" $NODELIST|awk -F: '{print $1}')
  if [ $HID -le $DATANODES ] ;then
  [ -z $DEBUG_HADOOP ] ||  echo "Start datanodes!"
    mkdir $LDIR/data
    bash --norc $HADOOP_HOME/sbin/hadoop-daemon.sh --config $CONFIG --script start namenode  > $LOGS/hadoop.namenode.$HID 2>&1 
    sleep 5
  fi
# Running the datanode cause the socket binding to fail for the nodemanager  
#  [ -z $DEBUG_HADOOP ] || echo "Starting hadoop Datanode  on $ID"
#    bash --norc $HADOOP_HOME/sbin/hadoop-daemon.sh --config $CONFIG --script hdfs start datanode  > $LOGS/hadoop.datanode.$ID 2>&1 

  [ -z $DEBUG_HADOOP ] || echo "Starting Yarn NodeManager on $ID"
  if [ ! -z $HADOOP_PRELOAD ] ; then
    export LD_PRELOAD=$HADOOP_PRELOAD
  fi
  # Note this should NOT be the daemon
  # Daemon will return and leave a job that could be killed alps. nohup will not work.
  # There is also no start or stop in this command as noted below
  bash --norc $HADOOP_HOME/bin/yarn --config $CONFIG  nodemanager > $LOGS/yarn.nodemanager.$ID 2>&1
#  $HADOOP_HOME/sbin/yarn-daemon.sh --config $CONFIG start nodemanager
  echo "Yarn Nodenanager exits at $ID"
  cleanup
fi
